name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: "Test (Go: ${{ matrix.go-version }}, Postgres: ${{ matrix.pg-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19", "1.20"]
        pg-version: [13, 14, 15]
      fail-fast: false
    env:
      PGLOGREPL_TEST_CONN_STRING: "postgres://pglogrepl:secret@127.0.0.1/pglogrepl?replication=database"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Stand up Postgres ${{ matrix.pg-version }}
        run: docker-compose up -d postgres
        env:
          POSTGRES_VERSION: ${{ matrix.pg-version }}
      - name: Run tests
        run: go test -v -race ./...
